services:
  pgadmin:
    image: "dpage/pgadmin4:8"
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USERNAME}@example.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5050:5050
    volumes:
      - "./pgadmin/config/servers.json:/pgadmin4/servers.json"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    user: postgres
    image: "postgres:16"
    # Log all queries - very noisy
    # command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_TARGET_DB=superset
      - SUPERSET_USER=superset
      - SUPERSET_PASSWORD=superset
      - SUPERSET_DB=superset
      - CYBERMETRICS_USER=cybermetrics
      - CYBERMETRICS_PASSWORD=cybermetrics
      - CYBERMETRICS_DB=cybermetrics
    ports:
      - 5432:5432
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./postgres/config/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
#      - ./postgres/import:/import
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  superset:
    image: "apache/superset"
    environment:
      - SUPERSET_CONFIG_PATH=/etc/superset/superset_config.py
      - SUPERSET_SECRET_KEY=123123123123
      - ADMIN_PASSWORD=admin
    ports:
      - 8080:8088
    volumes:
      - ./superset/data:/etc/superset
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
