#!/bin/bash

export PGUSER=$POSTGRES_USERNAME

psql -c "CREATE USER ${SUPERSET_USER} WITH PASSWORD '${SUPERSET_PASSWORD}';"
psql -c "CREATE DATABASE ${SUPERSET_DB};"
psql -c "GRANT ALL PRIVILEGES ON DATABASE ${SUPERSET_DB} TO ${SUPERSET_USER};"
psql -d "${SUPERSET_DB}" -c "GRANT ALL ON SCHEMA public TO ${SUPERSET_USER};"

psql -c "CREATE USER ${CYBERMETRICS_USER} WITH PASSWORD '${CYBERMETRICS_PASSWORD}';"
psql -c "CREATE DATABASE ${CYBERMETRICS_DB};"
psql -c "GRANT ALL PRIVILEGES ON DATABASE ${CYBERMETRICS_DB} TO ${CYBERMETRICS_USER};"
psql -d "${CYBERMETRICS_DB}" -c "GRANT ALL ON SCHEMA public TO ${CYBERMETRICS_USER};"

# psql -d "$POSTGRES_TARGET_DB" -f /import/dump.sql
